GET http://localhost:3000

### with a project name only
GET http://localhost:3000/api/issues/test


### with all fields and a project name
POST http://localhost:3000/api/issues/test
Content-Type: application/json

{
  "issue_title": "REST CLIENT Fix error in posting data",
  "issue_text": "When we post data it has an error.",
  "created_by": "Joe",
  "assigned_to": "Joe",
  "status_text": "In QA"
}

### with a project name and, a character to escape and required fields only
POST http://localhost:3000/api/issues/test
Content-Type: application/json

{
  "issue_title": "<script>alert(‘XSS’)</script>",
  "issue_text": "When we post data it has an error.",
  "created_by": "Joe"
}

### with a project name and required fields only
POST http://localhost:3000/api/issues/test
Content-Type: application/json

{
  "issue_title": "REST CLIENT Fix error in posting data",
  "issue_text": "When we post data it has an error.",
  "created_by": "Joe"
}

### with all except "open"
POST http://localhost:3000/api/issues/test
Content-Type: application/json

{
  "issue_title": "REST CLIENT Fix error in posting data",
  "issue_text": "When we post data it has an error.",
  "created_by": "Joe",
  "assigned_to": "Joe",
  "status_text": "In QA"
}

### a project name and missing required fields
POST http://localhost:3000/api/issues/test
Content-Type: application/json

{
}